{% set data = load_setup_py_data() %}

package:
  name: pycalrissian
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python setup.py install
  number: 1

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pyyaml
    - kubernetes
    - loguru



about:
  home: https://github.com/terradue/pycalrissian
  license: Apache
  summary: "Python client for Calrissian - CWL on kubernetes"
